# Git sync
dags:
  persistence:
    # Enable persistent volume for storing dags
    enabled: true
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client
    # access mode of the persistent volume
    accessMode: ReadWriteMany

  gitSync:
    enabled: true

    # git repo clone url
    # ssh examples ssh://git@github.com/apache/airflow.git
    # git@github.com:apache/airflow.git
    # https example: https://github.com/apache/airflow.git
    repo: https://github.com/gabrielmichelwizeline/DEB-capstone-project-dags.git
    branch: master
    rev: HEAD
    depth: 1
    # the number of consecutive failures allowed before aborting
    maxFailures: 0
    # subpath within the repo where dags are located
    # should be "" if dags are at repo root
    subPath: "dags"


logs:
  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    # Volume size for logs
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName: nfs-client

env:
  - name: "NEW_FILES_PREFIX"
    value: "new/"
  - name: "PROCESSED_FILES_PREFIX"
    value: "processed/"
  - name: "BUCKET_NAME"
    value: "load-user-purchases-bucket"
  - name: "POSTGRES_TABLE"
    value: "user_purchase"
  - name: "POSTGRES_SCHEMA"
    value: "bootcampdb"
  - name: "SLACK_HTTP_CONNECTION_ID"
    value: "slack_connection"
  - name: "SLACK_WEBHOOK_TOKEN"
    value: "SLACK_WEBHOOK_TOKEN"
  - name: "SLACK_CHANNEL"
    value: "#dataengbootcamp-wizeliners"
  - name: "S3_SENSOR_DAG_NAME"
    value: "s3_sensor_postgres_pipeline"

